### PR TITLE
 fix OOMError caused by broadcastModel.cloneModule in DistributeOptimizer 

### LINKED ISSUE #1632: Distrioptimizer doesn't support huge model
When initThreadModels, Distrioptimizer will use cloneModule to clone model for each local thread.
But cloneModule is using SerializationUtils, if parameters is bigger than maximum buffer size, cloneModule will throw an OOMError. Like:
```
val model = Linear(262144, 1024)
val model2 = model.cloneModule()
```

```
An exception or error caused a run to abort. 
java.lang.OutOfMemoryError
	at java.io.ByteArrayOutputStream.hugeCapacity(ByteArrayOutputStream.java:123)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:117)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.flush(ObjectOutputStream.java:1822)
	at java.io.ObjectOutputStream.flush(ObjectOutputStream.java:719)
	at java.io.ObjectOutputStream.close(ObjectOutputStream.java:740)
	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:161)
	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:179)
	at org.apache.commons.lang3.SerializationUtils.clone(SerializationUtils.java:82)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.cloneModule(AbstractModule.scala:383)
	at com.intel.analytics.bigdl.models.WideDeepSpec$$anonfun$3.apply$mcV$sp(WideDeepSpec.scala:141)
	at com.intel.analytics.bigdl.models.WideDeepSpec$$anonfun$3.apply(WideDeepSpec.scala:138)
	at com.intel.analytics.bigdl.models.WideDeepSpec$$anonfun$3.apply(WideDeepSpec.scala:138)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1644)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1656)
	at com.intel.analytics.bigdl.models.WideDeepSpec.org$scalatest$BeforeAndAfter$$super$runTest(WideDeepSpec.scala:28)
	at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
	at com.intel.analytics.bigdl.models.WideDeepSpec.runTest(WideDeepSpec.scala:28)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1714)
	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1683)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1760)
	at com.intel.analytics.bigdl.models.WideDeepSpec.org$scalatest$BeforeAndAfter$$super$run(WideDeepSpec.scala:28)
	at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
	at com.intel.analytics.bigdl.models.WideDeepSpec.run(WideDeepSpec.scala:28)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

### PR DESCRIPTION
**Pull request by qiuxin2012**
## What changes were proposed in this pull request?

Support broadcast training model in ModelBroadcast.
Use ModelBroadcast to broadcast model in DistriOptimizer.
Reduce runtime memory consumption while caching models in DistriOptimizer.

## How was this patch tested?

unit tests, manual tests

## Related links or issues (optional)
fixed #1632

### CODE REVIEW

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala [hunk 1]
```diff
@@ -89,12 +90,17 @@ class ModelBroadcast[T: ClassTag](implicit ev: TensorNumeric[T]) extends Seriali
...
-    localModel: Module[T]): Unit = {
-    val localWeightBias = localModel.parameters()._1
+    localModel: Module[T], inference: Boolean = true): Unit = {
+    val (localWeightBias, localGradWeightBias) = localModel.parameters()
     var i = 0
     while (i < localWeightBias.length) {
       if (localWeightBias(i) != null) {
-        localWeightBias(i).set(broadcastWeightBias(i))
+        if (!inference) {
+          localWeightBias(i).resizeAs(broadcastWeightBias(i)).copy(broadcastWeightBias(i))
```
Comment (jason-dai) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: Even in training, we can still share weight and bias, no?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala [hunk 2]
```diff
@@ -89,12 +90,17 @@ class ModelBroadcast[T: ClassTag](implicit ev: TensorNumeric[T]) extends Seriali
...
+          localGradWeightBias(i).resizeAs(broadcastWeightBias(i))
```
Comment (jason-dai) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: We can do this in DistriOptimizer, instead of ModelBroadcast, yes?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala (hunk 1 above)
Comment (qiuxin2012) [reply spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: Seems good, and this can reduce some time for `putWeights`. Maybe also increase cache hits ratio.
Let's do it later in #1634.

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala (hunk 2 above)
Comment (qiuxin2012) [reply spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: It's not easy to init gradWeight and gradBias in DistriOptimizer....

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala (hunk 1 above)
Comment (qiuxin2012) [reply spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: I just check the code of initThreadModels.
The weight is shared after all sub models are cloned.
```
      val weights = cached.head._2
      cached.map(c =>
        if (!c._2.eq(weights)) {
          c._2.storage().set(weights.storage())
        }
      )
```

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala [hunk 3]
```diff
@@ -88,21 +95,39 @@ class ModelBroadcast[T: ClassTag](implicit ev: TensorNumeric[T]) extends Seriali
...
     }
+    // init gradient with a compacted storage
+    if (!inference) {
+      val storage = Storage[T](localGradWeightBias.map(_.nElement()).sum)
+      i = 0
+      while (i < localWeightBias.length) {
+        if (localWeightBias(i) != null) {
+          val wb = broadcastWeightBias(i)
+          if (!inference) {
+            localGradWeightBias(i).set(storage, wb.storageOffset(), wb.size(), wb.stride())
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: the localGradWeigthBias looks not correct. Is it should be same with wb, but here it use a new storage. So it will be all zero.

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala [hunk 4]
```diff
@@ -88,21 +95,39 @@ class ModelBroadcast[T: ClassTag](implicit ev: TensorNumeric[T]) extends Seriali
...
       i += 1
     }
+    // init gradient with a compacted storage
+    if (!inference) {
+      val storage = Storage[T](localGradWeightBias.map(_.nElement()).sum)
+      i = 0
+      while (i < localWeightBias.length) {
+        if (localWeightBias(i) != null) {
+          val wb = broadcastWeightBias(i)
+          if (!inference) {
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: duplicate !inference

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala [hunk 5]
```diff
@@ -88,21 +95,39 @@ class ModelBroadcast[T: ClassTag](implicit ev: TensorNumeric[T]) extends Seriali
...
+    val (localWeightBias, localGradWeightBias) = localModel.parameters()
     var i = 0
     while (i < localWeightBias.length) {
       if (localWeightBias(i) != null) {
         localWeightBias(i).set(broadcastWeightBias(i))
       }
       i += 1
     }
+    // init gradient with a compacted storage
+    if (!inference) {
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: I think you should move this logic to a separated function. It has nothing to do with the putWeightBias function

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala [hunk 6]
```diff
@@ -25,12 +25,13 @@ import org.apache.spark.broadcast.Broadcast
...
- * Note: do not use it in model training since the broadcast models share weights and biases
- * It shortens the broadcast time, which is especially useful when the model size is large
+ * ModelBroadcast is used to broadcast model.
+ * Note: If you want to use this to broadcast training model, please set inference = false.
+ * @param inference inference or training.
  * @tparam T data type
  */
-class ModelBroadcast[T: ClassTag](implicit ev: TensorNumeric[T]) extends Serializable {
+class ModelBroadcast[T: ClassTag](
+      inference: Boolean = true)(implicit ev: TensorNumeric[T]) extends Serializable {
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: inference -> compactParameter?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/optim/DistriOptimizer.scala [hunk 7]
```diff
@@ -523,7 +518,13 @@ object DistriOptimizer {
...
     )(implicit ev: TensorNumeric[T]) = {
     val sc = dataset.originRDD().sparkContext
-    val broadcast = sc.broadcast((model, criterion, state, validationMethods, optimMethod))
+    val broadcast = sc.broadcast((criterion, state, validationMethods, optimMethod))
+    // As cloneModel is using Serialization to implement deep copy, and will throw OOMError
+    // when model's size is bigger than SerializationUtils' buffer size. So we can use
+    // ModelBroadcast to clone model here.
+    // Notes: All models returned by modelBroadcast.value() share the same weight&bias, while
+    // gradWeight&gradBias is unshared.
+    val modelBroadcast = ModelBroadcast[T](false).broadcast(sc, model)
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/optim/DistriOptimizer.scala]: Will it be OOM when broadcast weightAndBias?

Comment (yiheng) [reply spark/dl/src/main/scala/com/intel/analytics/bigdl/optim/DistriOptimizer.scala]: I think it's a bug of cloneModule. We should fix it or at least add a warning in the document of the method

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/optim/DistriOptimizer.scala [hunk 8]
```diff
@@ -563,14 +564,8 @@ object DistriOptimizer {
...
 
-      val weights = cached.head._2
-      cached.map(c =>
-        if (!c._2.eq(weights)) {
-          c._2.storage().set(weights.storage())
-        }
-      )
-
       logger.info("model thread pool size is " + Engine.model.getPoolSize)
+      val weights = cached.head._2
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/optim/DistriOptimizer.scala]: where do you use the weights?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/optim/DistriOptimizer.scala [hunk 9]
```diff
@@ -251,28 +250,24 @@ object DistriOptimizer {
...
               val length = taskSize + (if (tid < extraTask) 1 else 0)
-              var i = 0
+              var i = 1
               while (i < cached.modelGradients.length) {
-                if (i == 0) {
-                  cached.gradient.narrow(1, offset + 1, length)
-                    .copy(cached.modelGradients(i).narrow(1, offset + 1, length))
-                } else {
-                  cached.gradient.narrow(1, offset + 1, length)
+                  cached.modelGradients(0).narrow(1, offset + 1, length)
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/optim/DistriOptimizer.scala]: Maybe I miss it, do you remove the useless cached.gradient?

Comment (dding3) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/optim/DistriOptimizer.scala]: If we directly aggregate other model's gradient to the first model's, there is a chance it's not correct if we turn on drop percentage as there is a possibility the first model's bp has not finished yet. I am not sure if we need consider this situation now.

Comment (qiuxin2012) [reply spark/dl/src/main/scala/com/intel/analytics/bigdl/optim/DistriOptimizer.scala]: Yes, removed.

**Comment by qiuxin2012** [comment]
jenkins passed
