### PR TITLE
bugfix for SparseJoinTable

### LINKED ISSUE #1674: Support transfer SparseTensor back to python

### LINKED ISSUE #1932: SparseJoinTable with inconsistent sparse tensor input would get ArrayIndexOutOfBoundsException
SparseJoinTable with inconsistent sparse tensor input would get ArrayIndexOutOfBoundsException. For example, some sparse tensor may have 3 indices, but some have 2 indices. 

Exception:

}/nn.SparseJoinTable(2)
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy$mcF$sp(TensorNumeric.scala:641)
	at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy(TensorNumeric.scala:635)
	at com.intel.analytics.bigdl.tensor.TensorNumericMath$TensorNumeric$NumericFloat$.arraycopy(TensorNumeric.scala:425)
	at com.intel.analytics.bigdl.tensor.SparseTensor$.concat(SparseTensor.scala:1178)
	at com.intel.analytics.bigdl.tensor.SparseTensor$.concat(SparseTensor.scala:1053)
	at com.intel.analytics.bigdl.tensor.Tensor$.sparseConcat(Tensor.scala:1268)
	at com.intel.analytics.bigdl.nn.SparseJoinTable.updateOutput(SparseJoinTable.scala:61)
	at com.intel.analytics.bigdl.nn.SparseJoinTable.updateOutput(SparseJoinTable.scala:36)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:280)
	at com.intel.analytics.bigdl.nn.Sequential.updateOutput(Sequential.scala:39)
	at com.intel.analytics.bigdl.nn.abstractnn.AbstractModule.forward(AbstractModule.scala:280)
	at com.intel.analytics.bigdl.optim.Predictor$$anonfun$predict$1$$anonfun$apply$3.apply(Predictor.scala:72)
	at com.intel.analytics.bigdl.optim.Predictor$$anonfun$predict$1$$anonfun$apply$3.apply(Predictor.scala:71)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.

### PR DESCRIPTION
**Pull request by qiuxin2012**
## What changes were proposed in this pull request?

bugfix for SparseJoinTable

## How was this patch tested?

unit tests

## Related links or issues (optional)
fixed #1932

### CODE REVIEW

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/tensor/SparseTensor.scala [hunk 1]
```diff
@@ -1099,6 +1099,44 @@ object SparseTensor{
...
+  private def lastIndexOf[T: ClassTag](
+        array: Array[T],
+        value: T,
+        start: Int,
+        end: Int)(implicit ev: TensorNumeric[T]): Int = {
+    if (start > end) return -1
+    require(end <= array.length - 1, s"indexOf end should't exceed array size ${array.length - 1}" +
+      s", but got $end")
+    var i = start
+    while (i < end && array(i) == value) {
```
Comment (zhangxiaoli73) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/tensor/SparseTensor.scala]: i can be equal end?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/tensor/SparseTensor.scala [hunk 2]
```diff
@@ -1099,6 +1099,44 @@ object SparseTensor{
...
+      i += 1
+    }
+    if (array(i) == value) {
+      i
+    } else {
+      i - 1
+    }
+  }
+
+  private def firstIndexOf[T: ClassTag](
```
Comment (zhangxiaoli73) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/tensor/SparseTensor.scala]: why the name is "first..."

Comment (qiuxin2012) [reply spark/dl/src/main/scala/com/intel/analytics/bigdl/tensor/SparseTensor.scala]: find the first index who equals value. I will add some scala doc for this method.
