### PR TITLE
fix: memory leak in `model.predictImageSet`.

### LINKED ISSUE #2535: Memory leak when using quantized model for prediction
The memory consumption grows steadily as multiple inferences running with quantized model. 

After some initial investigation, found the heap memory was actually small and consistent while the used physical memory is steadily increased.

### PR DESCRIPTION
**Pull request by i8run**
## What changes were proposed in this pull request?
There're three reasons of memory leak.

1. repeat allocations in bigquant, which will be fixed in BigDL-core.
2. repeat clone module but no release. `model.predictImageSet` will new
   Predictor again and again.
3. share weights.

Because of multi models architecture, every `LocalPredictor` will clone models.
For efficiency all cloned models and origin model will share the same parameters.
If we iterate and release all cloned models, the parameters of origin model will
be released also. So we should clone a new model first in `LocalPredictor`.

This patch add a `StorageManager` which contains a concurrent hash map
to maintain all allocations of native memory/resources and prevent
duplicate release. It's also helpful for debug.

## How was this patch tested?

Add a new test case and run Jenkins.

## Related links or issues (optional)
fixed #2535

### CODE REVIEW

**Comment by jason-dai** [comment]
Does distributed model predict have similar issues?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/tensor/Tensor.scala [hunk 1]
```diff
@@ -804,6 +804,8 @@ trait Tensor[T] extends Serializable with TensorMath[T] with Activity {
     }
     return false
   }
+
+  def toQuantizedTensor: QuantizedTensor[T]
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/tensor/Tensor.scala]: What's this for?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/utils/Util.scala [hunk 2]
```diff
@@ -166,6 +166,10 @@ object Util {
     var i = 0
     while (i < tensors.length) {
       if (tensors(i) != null) {
+        if (tensors(i).getTensorType == QuantizedType) {
+          tensors(i).toQuantizedTensor.release()
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/utils/Util.scala]: asInstanceof[...]?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/utils/Util.scala [hunk 3]
```diff
@@ -179,10 +183,23 @@ object Util {
...
     while (i < localWeightBias.length) {
       if (localWeightBias(i) != null) {
-        localWeightBias(i).set(broadcastWeightBias(i))
+        clearAndSet(localWeightBias(i), broadcastWeightBias(i))
       }
       i += 1
     }
+
+    def clearAndSet(old: Tensor[T], other: Tensor[T]): Unit = {
+      if (old.getTensorType == QuantizedType && other.getTensorType == QuantizedType) {
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/utils/Util.scala]: do this in the set method of quantized tensor?

Comment (i8run) [reply spark/dl/src/main/scala/com/intel/analytics/bigdl/utils/Util.scala]: It can't do `release` in the quentized tensor set method. Because if we have tensor A, B, C, than we do `A.set(B)` and `A.set(C)`. At the end, the `A` and `B` will be all released. This is not we want because we may want to reserve tensor `B`. So we only release the tensor carefully when needed.

**Comment by i8run** [comment]
@jason-dai Yes, it also has this problem. We're working on it. But it can not be fixed with the same method of `LocalPredictor`.  Because RDD is lazy. We can't release the resources in `mapPartition`, otherwise the `release` will be called before main part of `mapPartition`.

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala [hunk 4]
```diff
@@ -53,26 +59,45 @@ class ModelBroadcast[T: ClassTag](applyProtoBuffer: Boolean = false)
    * @return this
    */
   def broadcast(sc: SparkContext, model: Module[T]): this.type = {
+    CachedModels.deleteAll(uuid) // delete the models on driver
+
     if (applyProtoBuffer) {
-      broadcastModel = sc.broadcast(model)
+      broadcastModel = sc.broadcast(ModelInfo(uuid, model))
```
Comment (wzhongyuan) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: Why not add into `CachedModels` ?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala [hunk 5]
```diff
@@ -141,13 +173,92 @@ class ModelBroadcast[T: ClassTag](applyProtoBuffer: Boolean = false)
...
 
-
 object ModelBroadcast {
   def apply[@specialized(Float, Double) T: ClassTag](applyProtoBuffer: Boolean = false)
         (implicit ev: TensorNumeric[T]) : ModelBroadcast[T] = {
     new ModelBroadcast(applyProtoBuffer)
   }
 }
+
+class ModelInfo[T: ClassTag](val uuid: String, @transient var model: Module[T])(
```
Comment (wzhongyuan) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: case class ?

Comment (wzhongyuan) [reply spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: Why transient ? will it be ignored while serialized and deserialized between driver and executor ?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala [hunk 6]
```diff
@@ -141,13 +173,92 @@ class ModelBroadcast[T: ClassTag](applyProtoBuffer: Boolean = false)
...
+  def deleteAll[T: ClassTag](currentKey: String)(implicit ev: TensorNumeric[T]): Unit =
+    lock.synchronized {
+      ev.getType() match {
+        case FloatType =>
+          val keys = cachedFloatModels.keys
+          for (key <- keys) {
+            if (key != currentKey) {
+              val models = cachedFloatModels(key)
+              println(s"delete key = $key ${models.length}")
+              for (model <- models) { model.release()
```
Comment (wzhongyuan) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: Does `release` compatible for those models not quantized ?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala [hunk 7]
```diff
@@ -141,13 +173,92 @@ class ModelBroadcast[T: ClassTag](applyProtoBuffer: Boolean = false)
...
+                println(StorageManager.get().count(!_._2.isFreed))
```
Comment (wzhongyuan) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: remove the `println` clause ?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala [hunk 8]
```diff
@@ -141,13 +173,92 @@ class ModelBroadcast[T: ClassTag](applyProtoBuffer: Boolean = false)
...
+              }
+              cachedFloatModels.remove(key)
+              println(StorageManager.get().count(!_._2.isFreed))
```
Comment (wzhongyuan) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: remove the `println` clause ?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/nn/quantized/Desc.scala [hunk 9]
```diff
@@ -178,3 +181,28 @@ object QuantParams {
   val THRESHOLD = 127.0f
 }
 
+case class StorageInfo(descType: DescType, isFreed: Boolean)
+
+object StorageManager {
+  import java.util.concurrent.ConcurrentHashMap
+  private val nativeStorages: ConcurrentHashMap[Long, StorageInfo] = new ConcurrentHashMap()
+
+  def isFreed(nativeStorage: Long): Boolean = {
```
Comment (wzhongyuan) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/nn/quantized/Desc.scala]: Add comments.. also `isReleased` makes more sense ?

**Comment by yiheng** [comment]
Do you miss the change in bigdl core?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala [hunk 10]
```diff
@@ -38,10 +43,11 @@ import scala.reflect.ClassTag
 class ModelBroadcast[T: ClassTag](applyProtoBuffer: Boolean = false)
   (implicit ev: TensorNumeric[T]) extends Serializable {
 
-  private var broadcastModel: Broadcast[Module[T]] = _
+  private var broadcastModel: Broadcast[ModelInfo[T]] = _
   private var broadcastConsts: Broadcast[Map[String, Tensor[_]]] = _
   private var broadcastParameters: Broadcast[Array[Tensor[T]]] = _
 
+  val uuid: String = UUID.randomUUID().toString
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: private?

Comment (yiheng) [reply spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: why it's a `val`, for different predictions, should we use different uuid?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/nn/quantized/Desc.scala [hunk 11]
```diff
@@ -178,3 +181,28 @@ object QuantParams {
   val THRESHOLD = 127.0f
 }
 
+case class StorageInfo(descType: DescType, isFreed: Boolean)
+
+object StorageManager {
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/nn/quantized/Desc.scala]: private[bigdl]?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/nn/quantized/Desc.scala [hunk 12]
```diff
@@ -178,3 +181,28 @@ object QuantParams {
   val THRESHOLD = 127.0f
 }
 
+case class StorageInfo(descType: DescType, isFreed: Boolean)
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/nn/quantized/Desc.scala]: private[bigdl]?

File: spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala [hunk 13]
```diff
@@ -141,13 +173,92 @@ class ModelBroadcast[T: ClassTag](applyProtoBuffer: Boolean = false)
...
+
+  import scala.collection._
+  import scala.collection.convert.decorateAsScala._
+
+  val lock = new AnyRef
+
+  type FloatValues = ArrayBuffer[Module[Float]]
+  type DoubleValues = ArrayBuffer[Module[Double]]
+
+  private val cachedFloatModels: concurrent.Map[String, FloatValues] =
```
Comment (yiheng) [inline spark/dl/src/main/scala/com/intel/analytics/bigdl/models/utils/ModelBroadcast.scala]: Why there're two arraybuffer here?

**Comment by yiheng** [comment]
should we also release memory in DistOptimizer and LocalOptimizer?

**Comment by wzhongyuan** [comment]
I refined per review and merged to @i8run 's branch, please run a PR job

**Comment by wzhongyuan** [comment]
PR validation passed http://mlt-bddl01.sh.intel.com:8080/job/BigDL-PRVN-lite/72/
